name: Deploy project to our server

on:
  push:
    branches:
      - deploy-live

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 72.62.120.217
          username: secaax-ftp
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          timeout: 120000
          server-dir: /
          dangerous-clean-slate: false
